# enable labeler on issues, prs, or both.
enable:
  issues: true
  prs: true

comments:
  prs: |
    Labeler가 제목과 설명에 있는 특별한 텍스트와 일치하는 레이블을 적용했습니다.
    Label을 검토하고 필요한 변경 사항을 적용해 주세요.

labels:
  'Component':
    include:
      - '\bComponent\b'
  'Fix':
    include:
      - '\bFix\b'
  'Bug':
    include:
      - '\bBug\b'
  'Page':
    include:
      - '\bPage\b'
  'Docs':
    include:
      - '\bDocs\b'
  'Setting':
    include:
      - '\bSetting\b'
  'Refactoring':
    include:
      - '\bRefactoring\b'
  'Help wanted':
    include:
      - '\binclude\b'
  'Test':
    include:
      - '\bTest\b'
  'Featuring':
    include:
      - '\bFeaturing\b'
