name: 'Auto Milestone Assign'

on:
  pull_request:
    types: [opened, reopened, edited]
  issues:
    types: [opened, reopened, edited]
  

jobs:
  assign-milestone:
    runs-on: ubuntu-latest

    steps:
      - uses: zoispag/action-assign-milestone@v1
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          milestone: '7월 2주차 Sprint'
