name: Release Drafter
on:
  push:
    branches:
      - OZ-80-F-QA-4
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        # (Optional)
        # workflow 에서 여러 구성이 필요할 때 config-name 에 오버라이드 해줍니다.
        # 반드시 .github/ 에 위치해야합니다.
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}